version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-status-hub
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - status-hub
  status-hub-be:
    build:
      context: .
      dockerfile: ../packages/backend/Dockerfile
    container_name: status-hub-backend
    volumes:
      - status-hub-data:/prod/status-hub-backend/data
    ports:
      - 8420:8420
      - 8419:8419
    environment:
      - GITHUB_AUTH_CLIENT_ID=client_id
      - GITHUB_AUTH_CLIENT_SECRET=secret
      - GITHUB_AUTH_REDIRECT_URL=http://localhost:8418/api/auth/login/github/callback
      - GITHUB_CLIENT_ID=client_id
      - GITHUB_CLIENT_SECRET=secret
      - GITHUB_REDIRECT_URL=http://localhost:8418/api/route/adapter/github/callback
      - SPOTIFY_CLIENT_ID=client_id
      - SPOTIFY_CLIENT_SECRET=secret
      - SPOTIFY_REDIRECT_URL=http://localhost:8418/api/route/adapter/spotify/callback
      - RESEND_API_KEY=resend_api_key
      - RESEND_SENDER_ADDR=no-reply@example.com
      - BULLMQ_REDIS_URL=redis://redis-status-hub:6379
      - BULL_MQ_PANEL_PORT=8419
      - NODE_ENV=production
    networks:
      - status-hub
  status-hub-fe:
    build:
      context: .
      dockerfile: ../packages/backend/Dockerfile
    container_name: status-hub-frontend
    ports:
      - 8418:3000
    environment:
      - BACKEND_BASE_URL=http://status-hub-backend:8420
      - NODE_ENV=production
    networks:
      - status-hub
volumes:
  redis-data:
  status-hub-data:
networks:
  status-hub:
