version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-status-hub
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - status-hub
  status-hub:
    build:
      context: .
      dockerfile: ./aio.Dockerfile
    restart: always
    volumes:
      - status-hub-data:/prod/status-hub-backend/data
    ports:
      - 8420:8420
      - 8419:8419
      - 8418:3000
    networks:
      - status-hub
    environment:
      - GITHUB_AUTH_CLIENT_ID=client_id
      - GITHUB_AUTH_CLIENT_SECRET=secret
      - GITHUB_AUTH_REDIRECT_URL=http://localhost:8418/api/auth/login/github/callback
      - GITHUB_CLIENT_ID=client_id
      - GITHUB_CLIENT_SECRET=secret
      - GITHUB_REDIRECT_URL=http://localhost:8418/api/route/adapter/github/callback
      - SPOTIFY_CLIENT_ID=client_id
      - SPOTIFY_CLIENT_SECRET=secret
      - SPOTIFY_REDIRECT_URL=http://localhost:8418/api/route/adapter/spotify/callback
      - RESEND_API_KEY=resend_api_key
      - RESEND_SENDER_ADDR=no-reply@example.com
      - BULLMQ_REDIS_URL=redis://redis-status-hub:6379
      - BULL_MQ_PANEL_PORT=8419
      - NODE_ENV=production
volumes:
  redis-data:
  status-hub-data:
networks:
  status-hub:
